### ISSUE TITLE
请教一个问题，就是点击日历的时候是您自己封装的颜色   我另外改的话就有冲突了 QQ623681975

### ISSUE THREAD

**Issue by fengxinhao** [slailcp/selectDate#2]

**Comment by BingGanCS** [comment]
![tim 20180509172653](https://user-images.githubusercontent.com/32862600/39807233-5fb57bec-53ae-11e8-80cf-1acb84419ca6.png)
切换日历时候另一个月的还有这个class
![image](https://user-images.githubusercontent.com/32862600/39807283-7ecb3e0e-53ae-11e8-9ef0-64d120b37aba.png)
